stages:
  - build

linux:
  stage: build
  cache:
    paths:
      - cache/
  variables:
    TOXCORE_REPO: "TokTok/c-toxcore"
    GL_BUILD: "lin64"
  before_script:
    - ./extra/gitlab/linux-before.sh
  script:
    - ./extra/gitlab/linux-script.sh

windows:
  stage: build
  cache:
    paths:
      - cache/
  variables:
    TOXCORE_REPO: "TokTok/c-toxcore"
    GL_BUILD: "win64"
  before_script:
    - ./extra/gitlab/windows-before.sh
  script:
    - ./extra/gitlab/windows-script.sh

windows_legacy:
  stage: build
  cache:
    paths:
      - cache/
  variables:
    TOXCORE_REPO: "TokTok/c-toxcore"
    GL_BUILD: "winXP"
  before_script:
    - ./extra/gitlab/windows_legacy-before.sh
  script:
    - ./extra/gitlab/windows_legacy-script.sh
